=== Salvatore-Di-Costanzo/jaxb/src/main/java/schema/schema.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="PreservationConfiguration">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="MaxPDVSize" type="xsd:nonNegativeInteger" minOccurs ="1" maxOccurs="1"/>
<xsd:element name="MaxPDVDocs" type="xsd:nonNegativeInteger" minOccurs ="1" maxOccurs="1"/>
<xsd:element name="ClassiDocumentali">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ClasseDocumentale" type ="DocumentType"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:complexType name ="DocumentType">
<xsd:sequence>
<xsd:element name="id" type="xsd:string" minOccurs ="1" maxOccurs="1"/>
<xsd:element name="terminiConservazione" type="xsd:nonNegativeInteger" minOccurs ="1" maxOccurs="1"/>
<xsd:element name ="mappings" type="mappingsType"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name ="mappingsType">
<xsd:sequence>
<xsd:element name="metadataSystem" type ="metadataSystemType" maxOccurs="unbounded" minOccurs="1"/>
<xsd:element name="metadataCustom" type ="metadataCustomType" maxOccurs="unbounded" minOccurs="1"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="metadataCustomType">
<xsd:sequence>
<xsd:element name="docPrincipale" type ="metadataDoc" maxOccurs="unbounded" minOccurs="1"/>
<xsd:element name="allegati" type ="metadataAllegati" maxOccurs="unbounded" minOccurs="1"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="metadataSystemType">
<xsd:sequence>
<xsd:element name="docPrincipale" type ="metadataDoc" maxOccurs="unbounded" minOccurs="1"/>
<xsd:element name="allegati" type ="metadataAllegati" maxOccurs="unbounded" minOccurs="1"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="keyType">
<xsd:attribute type="xsd:string" name="field" use ="required"/>
<xsd:attribute type="xsd:string" name="name" use ="required"/>
<xsd:attribute type="xsd:string" name="valuetype" use ="required"/>
<xsd:attribute type="xsd:string" name="fieldtype" use ="required"/>
<xsd:attribute type="xsd:boolean" name="mandatoryForPreservation" use ="required"/>
    <!-- Sostituito: -->
    <!-- <xsd:attribute type="xsd:boolean" name="preservationPurpose" minOccurs="1" use ="required"/> -->
<xsd:attribute type="xsd:boolean" name="preservationPurpose" use ="required"/>
</xsd:complexType>

<xsd:complexType name ="metadataDoc">
<xsd:sequence>
<xsd:element name="key" type ="keyType" maxOccurs="unbounded" minOccurs="1"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name ="metadataAllegati">
<xsd:sequence>
<xsd:element name="key" type ="keyType" maxOccurs="unbounded" minOccurs="1"/>
</xsd:sequence>
</xsd:complexType>
</xsd:schema>

=== Salvatore-Di-Costanzo/jaxb/src/main/java/schema/schema.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<PreservationConfiguration xsi:noNamespaceSchemaLocation="schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <MaxPDVSize>699</MaxPDVSize>
  <MaxPDVDocs>3183</MaxPDVDocs>
  <ClassiDocumentali>
    <ClasseDocumentale>
      <id>string</id>
      <terminiConservazione>2957</terminiConservazione>
      <mappings>
        <metadataSystem>
          <docPrincipale>
            <key field="string" name="string" valuetype="string" fieldtype="string" mandatoryForPreservation="false" preservationPurpose="0" />
          </docPrincipale>
          <allegati>
            <key field="string" name="string" valuetype="string" fieldtype="string" mandatoryForPreservation="0" preservationPurpose="false" />
          </allegati>
        </metadataSystem>
        <metadataCustom>
          <docPrincipale>
            <key field="string" name="string" valuetype="string" fieldtype="string" mandatoryForPreservation="false" preservationPurpose="0" />
          </docPrincipale>
          <allegati>
            <key field="string" name="string" valuetype="string" fieldtype="string" mandatoryForPreservation="true" preservationPurpose="true" />
          </allegati>
        </metadataCustom>
      </mappings>
    </ClasseDocumentale>
  </ClassiDocumentali>
</PreservationConfiguration>
